{% set version = "1.3.0" %}
{% set sha256 = "3b884a80d872f7cfaf5b351aa90af4afaadc02588a764e1071de56963d6cbcb8" %}

package:
  name: flask-bower
  version: '{{ version }}'

source:
  url: https://pypi.python.org/packages/source/F/Flask-Bower/Flask-Bower-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - flask >=0.9

test:
  requires:
    - python {{ python_min }}
  imports:
    - flask_bower

about:
  home: https://github.com/lobeck/flask-bower
  license: GPL-2.0
  license_family: GPL
  summary: An extension to manage and serve your javascript assets with bower

extra:
  recipe-maintainers:
    - corburn
